# Generated by Django 4.2.7 on 2023-11-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cta',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='cta',
            name='slug',
        ),
    ]
