# Generated by Django 4.2.7 on 2023-11-20 22:06

import apps.dealSection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealSection', '0002_auto_20231120_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsection',
            name='image_url',
            field=models.ImageField(default='default', upload_to=apps.dealSection.models.DealSection_directory),
            preserve_default=False,
        ),
    ]
