# Generated by Django 3.2.16 on 2023-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20231120_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='comment',
            field=models.CharField(default='Nuevo comentario único', max_length=255, unique=True),
        ),
    ]
