# Generated by Django 3.2.16 on 2023-11-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='comment',
            field=models.CharField(default='Nuevo comentario único', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
