# Generated by Django 4.2.7 on 2023-11-21 04:10

import apps.about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20231120_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_url',
            field=models.ImageField(default='default', upload_to=apps.about.models.About_directory),
            preserve_default=False,
        ),
    ]
