# Generated by Django 4.2.7 on 2023-11-21 05:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_about_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
