# Generated by Django 3.2.16 on 2023-11-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'incentive',
                'verbose_name_plural': 'incentives',
            },
        ),
    ]
