# Generated by Django 4.2.7 on 2023-11-20 22:06

import apps.incentive.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='image_url',
            field=models.ImageField(upload_to=apps.incentive.models.Incentive_directory),
        ),
    ]
