# Generated by Django 4.2.7 on 2023-11-21 05:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0003_alter_incentive_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
