# Generated by Django 3.2.16 on 2023-11-20 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='defaul', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
