# Generated by Django 3.2.16 on 2023-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationPlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationplan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vacationplan',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='vacationplan',
            name='slug',
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='country',
            field=models.CharField(default='Venezuela', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='image_url',
            field=models.CharField(default='Defaul img', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacationplan',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
            preserve_default=False,
        ),
    ]
